### ISSUE TITLE
storage class questions

### ISSUE THREAD

**Issue by GerryLon** [yunify/qingstor-csi#41]
在readme中的storage class example:
```yaml
 apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    name: csi-neonsan
  provisioner: neonsan.csi.qingstor.com
  parameters:
    fsType: "ext4"
    rep_count: "2"
    pool_name: "kube"
  reclaimPolicy: Delete 
```
我想知道, 这个写法, 文件最终会存在哪里?
我们现在用的青云的私有云服务, 想把其中的存储提供给k8s来用.

谢谢!
